### ISSUE TITLE
Optimize the sandbox environment

### ISSUE THREAD

**Issue by kiennt** [hermanzdosilovic/judge0#2]
Currently, judge0 is creating new sandbox environment everytime it evaluates a job
I think there are 2 issues with this approach:

+ Initialize and delete a sandbox is cost time. Sandbox could be reused for many submissions
+ Sandbox id is equal to submission id. But `isolate` only allow limited number of sandbox id (default value is 1000), so after we running out of this value, `isolate` will die

https://github.com/ioi/isolate/blob/master/isolate.c#L256

**Comment by hermanzdosilovic** [comment]
Hi @kiennt,

> * Initialize and delete a sandbox is cost time. Sandbox could be reused for many submissions

there is a discussion on [isolate](https://github.com/ioi/isolate) project about this. You can read about it [here](https://github.com/ioi/isolate/issues/8).

Aside from having clean sandbox environment every time you want to run an untrusted program there is one more reason why we cannot reuse sandbox environment. In production you can run multiple parallel workers and actually we are doing that as defined in [docker-compose.prod.yml](https://github.com/hermanzdosilovic/judge0/blob/master/api/docker-compose.prod.yml#L40) file (two workers are run). If we didn't have separated sandbox environment, then two untrusted programs could be in the same sandbox environment - and we don't want that.

> * Sandbox id is equal to submission id. But `isolate` only allow limited number of sandbox id (default value is 1000), so after we running out of this value, `isolate` will die

You are totally right with this one :smile: We can set the maximum number of boxes using [default.cf](https://github.com/ioi/isolate/blob/3bf44c474f4777d95f304fa5de04a3972d72a807/default.cf#L18) file. I am thinking about setting this value to `2147483647` i.e. (1 << 31) - 1, and then initializing sandbox with id equal to `submission.id % 2147483647`

**Comment by kiennt** [comment]
hi @hermanzdosilovic you are right.

My initial thought was we create about N boxes. And then each submission will be shared by N.
E.g:
N = 10, submission = 41 will be put in the box with id 1. All the file of submission will be put in the folder `/box/1/41`. The cons of this approach your already mentioned we could have 2 untrusted programs run in the same box which could make them change each other. 

Of course your solution with `submission.id % maximum box` works too

**Comment by hermanzdosilovic** [comment]
Thanks @kiennt for this discussion. I have already implemented (#3) a second solution you mentioned. I will merge that to develop branch and in a few days we will have new release with this fix! :smile:
