### ISSUE TITLE
Free Pascal support

### ISSUE THREAD

**Issue by khangprolxag** [hermanzdosilovic/judge0#4]
hi, can you help to add new language like FPC??

**Comment by hermanzdosilovic** [comment]
@khangprolxag take a look at #7 to see how to add new language. :smile:

**Comment by khangprolxag** [comment]
nice :+1:  then i must build the container again right?

**Comment by khangprolxag** [comment]
hi, can you tell me how can i edit the image file?? i try to use docker cp command but it just copy to a container.

**Comment by hermanzdosilovic** [comment]
@khangprolxag 

You first need to build `judge0-base` image, and then you need to build `judge0-api` image.

1. Switch to branch `pascal`
2. In `base` folder run:
```
$ docker build -t hermanzdosilovic/judge0-base .
```
3. After that in `api` folder run:
```
$ docker build -t hermanzdosilovic/judge0-api
```
4. You can now run judge0 with Pascal supported.

**Comment by khangprolxag** [comment]
I build it on window but I found this error
"SECURITY WARNING: You are building a Docker image from Windows against a non-Win dows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories."
and I startup the api nothing have change.?

**Comment by hermanzdosilovic** [comment]
As a non-Windows user I am not familiar with this problem, but I am quite sure that it's not problem with the Dockerfile. I will merge this feature in the few days so you will be able to try this on [judge0.com](http://judge0.com)

**Comment by khangprolxag** [comment]
:D I fixed, can you show me how to change info on the website? I want to translate it to Vietnamese. Thank you!

**Comment by hermanzdosilovic** [comment]
On what website would you like to change info? If you want to translate API docs which can be found on [api.judge0.com](https://api.judge0.com) you need to change [API.md](https://github.com/hermanzdosilovic/judge0/blob/master/api/docs/API.md) file. And when you build again Production API image (`docker build -t hermanzdosilovic/judge0-api .`) your docs in Vietnamese will be generated.

**Comment by khangprolxag** [comment]
thank you. I got it!

**Comment by khangprolxag** [comment]
or edit theme like font, some character error with roboto  default font api using.

**Comment by hermanzdosilovic** [comment]
As defined in [Dockerfile](https://github.com/hermanzdosilovic/judge0/blob/master/api/Dockerfile#L19), documentation is generated using [aglio](https://github.com/danielgtaylor/aglio). For themes and other stuff about generating documentation please consult with their project docs - [here](https://github.com/danielgtaylor/aglio)

**Comment by khangprolxag** [comment]
I've seen it but when I change docs.html, nothing changed when I rebuild API?

**Comment by hermanzdosilovic** [comment]
@khangprolxag: after rebuilding API try deleting your old containers before starting API again. That's all I can do to help you. Thanks!
