### ISSUE TITLE
Support for C#

### ISSUE THREAD

**Issue by hermanzdosilovic** [hermanzdosilovic/judge0#8]
Add support for C#

**Comment by Att4ck3rS3cur1ty** [comment]
Sorry, I didn't understand very well your request. Can you, please, give further explanations?

**Comment by hermanzdosilovic** [comment]
Hi @Att4ck3rS3cur1ty,

this request is similar to #4. We would like to be able to run untrusted code written in C#. Currently, we support C, C++, Java, Ruby and Python. Pascal support is implemented in #7.

Let me know if you have any more questions.
